MathsPractice FLN/MSC/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
import Users

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('Users.urls')),
    path('practice/',include('practice.urls','practice')),



]

MathsPractice FLN/Users/urls.py
from django.urls import path
from Users import views


urlpatterns = [
    path('registration/',views.register,name='register' ),
    path('',views.register,name='index' ),
    path('home',views.home,name='home' ),


    path('login/',views.user_login,name='user_login' ),
    path('logout/',views.user_logout,name='user_logout' ),

    # path('staff_home/',views.staff_home,name='staff_home' ),
    # path('member_home/',views.member_home,name='member_home' ),
    # path('ad',views.admin_home,name='admin_home' ),
    # path('Staffperm',views.Staffperm,name='Staffperm' ),
    #  path('results/', views.SearchView.as_view(), name='search'),



    
]

MathsPractice FLN/practice/urls.py
from django.urls import path
from . import views

app_name="practice"
urlpatterns = [
    path('practice/',views.practicehome,name='practicehome' ),
    path('practice/Q1',views.practiceQ1,name='practiceQ1' ),

]

MathsPractice FLN/Users/models.py
from django.db import models
from django.contrib.auth.models import User


class Student(models.Model):
    username=models.CharField(max_length=200,null=True)
    password=models.CharField(max_length=200,null=True)
    def __str__(self):
        return self.username
    

# Create your models here.

MathsPractice FLN/practice/models.py
from django.db import models

# Create your models here.

MathsPractice FLN/Users/forms.py
from Users.models import Student

from django.forms import ModelForm

class User_Form(ModelForm):

    class Meta():
        model = Student
        fields="__all__"

MathsPractice FLN/Users/views.py
from django.shortcuts import render
from django.contrib.auth.models import User
from django.views.generic import ListView
from Users.models import Student
from django.contrib import messages
from practice.views import *
from django.shortcuts import redirect, render
from Users.forms import *
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from django.contrib.auth import authenticate, login, logout

def user_login(request):
    if request.method == "POST":
        user_name = request.POST.get('user_name')
        password = request.POST.get('password')

        user = Student.objects.get(username=user_name,password=password)

        if user:
            
            
            return render(request,'practice/practicehome.html')
           
        else:
            return HttpResponse("Please use correct id and password")
            

    else:
        return render(request, 'Users/login.html')


@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('index'))


# Create your views here.
def index(request):
    
   return render(request,'Users/homepage.html')


def register(request):

    registered = False
    messages=False
    if request.method == "POST":
        user_form = User_Form(data=request.POST)
        c=len(Student.objects.filter(username=request.POST['username'], password=request.POST['password']))
     

        if user_form.is_valid()  and c==0:
           
            user = user_form.save()
            
            user.save()

            

            registered = True
        if c>0:
            messages=True
            
       
    else:

        user_form = User_Form()
        

    return render(request, 'Users/registration.html',
                            {'registered':registered,
                             'user_form':user_form,'messages':messages})


def home(request):
    if request.user.is_authenticated:
        
        if  request.user.is_superuser:
                login(request,request.user)
                return redirect('admin_home')    
        elif request.user.is_staff:
            login(request,request.user)
            return redirect('staff_home')   
            
        else:
            login(request,request.user)
            return redirect('member_home')
    else:
        return redirect('index')

MathsPractice FLN/practice/views.py
from django.shortcuts import render,redirect
from .models import *
# Create your views here.
def practicehome(request):
    
    return render(request,'practice/practicehome.html')
def practiceQ1(request):
    
    return render(request,'practice/practiceQ1.html')

MathsPractice FLN/Users/templates/Users/homepage.html
{%extends 'Users/index.html'%}
{%block content%}

<header class="w3-display-container w3-content w3-wide" style="max-width:1500px;" id="home">
    <img class="w3-image" src="https://imgstaticcontent.lbb.in/lbbnew/wp-content/uploads/sites/1/2016/12/301216_SiriFortSportsComplex.jpg" alt="Architecture" width="1500" height="400">
    <div class="w3-display-middle w3-margin-top w3-center">
      <h1 class="w3-xxlarge w3-text-white"><span class="w3-hide-small w3-text" style="font-weight:800;color:black; ">Welcome to</span><br><br><br><span class="w3-padding w3-black w3-opacity-min"><b>MITTAL SPORTS COMPLEX</b></span> </h1>
    </div>
  </header>

{%endblock%}

MathsPractice FLN/Users/templates/Users/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
  
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
    <style>
      body{
        background-image: url('https://t3.ftcdn.net/jpg/02/85/48/82/360_F_285488226_byR6hPVcxZ5ncjoU2n6meOm9LRSPzOlR.jpg');
        background-size: cover;
      }
      </style>

    <title>MathsPractice FLN</title>
    
    

</head>
<body>
  <nav class="navbar navbar-expand-lg navbar-light" >
        <a class="navbar-brand" href="{%url 'index'%}">MathsPractice</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
      
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav mr-auto">
            
          
            {% if user.is_authenticated%}
            <li class="nav-item">
              <a class="nav-link" href="{%url 'user_logout'%}">Logout</a>

            </li>
          
          
            {%else%}
           
            <li class="nav-item active">
              <a class="nav-link" href="{%url 'user_login'%}">Login <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item active">
              <a class="nav-link" href="{%url 'register'%}">Register <span class="sr-only">(current)</span></a>
            </li>
            
          </ul>
          
          
         
          {%endif%}
        </div>
      </nav>
      
      
    {%block content%}



    {%endblock%}
    
  
    
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.14.7/dist/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
 
</body>
</html>

MathsPractice FLN/Users/templates/Users/login.html
{%extends 'Users/index.html'%}
{%block content%}
<br><br><br>
<div class="container mt-3" style="border:5px solid rgb(5, 5, 78); padding:30px;width:700px " >
<form method="POST" >
    {% csrf_token %}
    <label for="username"><h4 style="color:black">Username:</h4></label>
    <input type="text" name="user_name" placeholder="Username" class="form-control" style="width:500px">


    <label for="password"><h4 style="color:black">Password:</h4></label>
    <input type="password" name="password"  placeholder="Password"class="form-control" style="width:500px">
<br><br>
    <input type="submit" value="Login">


</form>
</div>









{%endblock%}

MathsPractice FLN/Users/templates/Users/memberpage.html
{%extends 'Users/index.html'%}
{%block content%}
{%load static%}

<div class=" container"><br>
    <h2 style="text-align:center">Sports</h2><br>
    <div class="row">
      {% for x in sport%}
      <div class="col-md-4">
        <div class="card card-3 mt-4">
          <h3><a href="/Sport/{{x.name}}">{{x.name}}</a></h3>
          <p></p><br>
          <p></p>
        </div>
      </div>
      
      {%endfor%}
    </div>
    
  </div>
  <br><br><br><br><br><br>





{%endblock%}

MathsPractice FLN/Users/templates/Users/registration.html
{%extends 'Users/index.html'%}
{%block content%}
{% if messages %}
<script> alert('The username or password already exist! Try again');
</script>
{% endif %}
{% if registered %}
    <div style="border:2px solid rgb(2, 2, 32);color:aqua">
  
<h2>You can now login</h2></div>
<a href="/login">LOGIN</a>
{% else %}
<br><br><br>
<div class="container" style="border:5px solid rgb(5, 5, 78); padding:30px;width:700px ; text-align: center;" >
    <h4 style="color:rgb(0, 2, 3); text-align:center">Enter Name and Password</h4>
    <br/>
    <form method="post" enctype="multipart/form-data" style="color:rgb(4, 0, 0); font-size: large;">
        {%csrf_token%}
       
        <label for="username"><h4 style="color:black">Username:</h4></label>
        {{user_form.username}}
<br/>

    <label for="password"><h4 style="color:black">Password :  </h4></label>
    {{user_form.password}}
       

       <br/>
       <br/>
        
        <input type="submit" value="Register" class="btn btn-primary btn-block" style="color:aliceblue">
    </form>
</div>
{% endif %}

{% endblock %}

MathsPractice FLN/practice/templates/practice/practicehome.html
{%extends 'Users/index.html'%}
{%block content%}
{%load static%}

 <br><br>
<div class="container ">
        
    <div style="margin:50px;padding:30px;text-align:center;border:2px solid black;font-family:Cambria, Cochin, Georgia, Times, 'Times New Roman', serif;font-weight:500">
    <h2><a href="{%url 'practice:practiceQ1'%}">Click Here to start QUIZ.</a></h2></div>

 
</div>
<div style="text-align:center;font-weight:400;color:black;font-family:Verdana, Geneva, Tahoma, sans-serif;font-size:xx-large">Instructions:<br>
    Total Marks is 10<br>    
</div>
 
{% endblock %}